
android:
  components:
    - android-26

env:
  global:
    - DOCKER_USER=robertkitzing
    - DOCKER_REPO=robertkitzing/liga-manager-ui

services:
  - docker

install:
  - export TAG=`grep '"version":' package.json | cut -d\" -f4`
  - yarn global add cordova
  - yarn global add typescript
  - yarn install
  - cd server && yarn install
  - cd ..

node_js:
  - "8"

cache:
  directories:
    - "node_modules"
    - "server/node_modules"

script:
  - yarn run build:web
  - yarn run build:app
  - yarn run build:server
  - docker build -t $DOCKER_REPO:$TAG-$TRAVIS_BUILD_NUMBER .
  - cd app
  - cordova platform add android
  - cordova build android --release -- --keystore="./limahb.keystore" --storePassword=$ANDROID_KEYSTORE_PASS --alias=limahb

after_success:
  - docker login -u $DOCKER_USER -p "$DOCKER_PASS"
  - docker push $DOCKER_REPO:$TAG-$TRAVIS_BUILD_NUMBER