env:
  global:
    - DOCKER_USER=robertkitzing
    - DOCKER_REPO=robertkitzing/liga-manager-ui

services:
  - docker

install:
  - export TAG=`grep '"version":' package.json | cut -d\" -f4`
  - yarn global add cordova 

node_js:
  - "8"

cache:
  directories:
    - node_modules

script:
  - yarn install
  - yarn run build:web
  - yarn run build:app
  - yarn run build:server
  - docker build -t $DOCKER_REPO:$TAG-$TRAVIS_BUILD_NUMBER .
  - yarn run cordova:build

after_success:
  - docker login -u $DOCKER_USER -p "$PENIS"
  - docker push $DOCKER_REPO:$TAG-$TRAVIS_BUILD_NUMBER