if: tag IS blank

branches:
  only:
  - master

language: android
android:
  components:
    - build-tools-26.0.2
    - android-27

rvm:
  - 2.2

env:
  global:
    - DOCKER_USER=robertkitzing
    - DOCKER_REPO=robertkitzing/liga-manager-ui

services:
  - docker

before_install:
  - sudo apt-add-repository ppa:brightbox/ruby-ng -y
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update
  - sudo apt-get --yes install ruby2.5 ruby2.5-dev
  - sudo apt-get --yes --no-install-recommends install yarn
  - openssl aes-256-cbc -K $encrypted_5a45bd5412da_key -iv $encrypted_5a45bd5412da_iv -in key.json.enc -out /home/travis/build/key.json -d
  - yarn --version

install:
  - nvm install 8
  - sudo gem install fastlane
  - export TAG=`grep '"version":' package.json | cut -d\" -f4`
  - export ANDROID_VERSION_CODE=$((30000 + $TRAVIS_BUILD_NUMBER))
  - yarn global add cordova
  - yarn global add typescript
  - yarn global add cordova-set-version
  - yarn global add @angular/cli
  - yarn install
  - cd server && yarn install
  - cd ..

cache:
  directories:
    - "node_modules"
    - "server/node_modules"
    - $HOME/.gradle

script:
  - yarn run build:web
  - yarn run build:app
  - yarn run build:server
  - docker build -t $DOCKER_REPO:$TAG-$TRAVIS_BUILD_NUMBER .
  - cd app
  - cordova platform add android
  - cordova-set-version -v $TAG -b $ANDROID_VERSION_CODE ./config.xml
  - cordova build android --release -- --keystore="./limahb.keystore" --storePassword=$ANDROID_KEYSTORE_STOREPASS --password=$ANDROID_KEYSTORE_PASS --alias=limahb
  - fastlane supply init --json_key /home/travis/build/key.json -p de.wildeligamanager.bremen
  - npm run createchangelog -- -v $ANDROID_VERSION_CODE
  - fastlane supply --apk /home/travis/build/RobertKitzing/liga-manager-ui/app/platforms/android/app/build/outputs/apk/release/app-release.apk --track beta -p de.wildeligamanager.bremen --json_key /home/travis/build/key.json

after_success:
  - docker login -u $DOCKER_USER -p "$DOCKER_PASS"
  - docker push $DOCKER_REPO:$TAG-$TRAVIS_BUILD_NUMBER