if: tag IS blank

git:
  depth: 3
  quiet: true

branches:
  only:
  - master
addons:
  chrome: stable
  firefox: latest

language: android
android:
  components:
    - build-tools-26.0.2
    - android-27

rvm:
  - 2.2

env:
  global:
    - MOZ_HEADLESS=1
    - DOCKER_USER=robertkitzing
    - DOCKER_REPO=robertkitzing/liga-manager-ui
    - secure: fO02T2gjC5XxeXp5QhswzX+encZQf9mA8y9bgkE9NywumdiygJSM+9WAndzgce9reIxD3Y4R0cUc28dyrlJXnrCeBy3pATnqmxI2rhAtAfNXmbz1lK/RNiGluXIKXOElCuaYGrDohYRYfJfUSD1L2GjHRXjjUOUKJJxcsKdjrUV0VKsy7m8dqo4jZrdiKpJY/dLKyOqNJ3tjXgQYOHARCP4MESvQOX2zKtJe5o1nYhl4f2kkXVH/eIdwLsrLl4/m20WoitS8iJcANWoK/16ZE0H08q2uYAI/iWfXlTNMMctyYoeKj6Ef8MQ6SA7G9MJrbYiaeRz3hwsF4RpA/gkioQ1A1LxaeBAZ8KMHYAX1s33/VYRCMWV1SUD+SJIdsCkduTL4dHS5CIk3CMvKxL9aSiEOzQfEvFGF8gjIQP/jn+87QMunoQc8KJTcjs0MlSEWhTe9RDZydgNEiDLRQmWj5dGbq1CqkldjbgOF8S0CUVAP13LHRmsu+FrSZqRVmiVonkvOPTAaROKDSr+vIiga5TgvxjWElYrAbtBXCqN+da7E9s/EeZP8ksLaAsNGcfabK9Ofu9MphbHHyyrFwSiFkgxkWnL7hOtjl/GsuUM0s8EL4JVKkqtT2XZEo+kWZ7twahuy37VG73zTrW0lW1IW02dI5F+U6/GytwfRa4UMcLY=
    - secure: "wLA6TVeFrfrf7uTHXXBEY5sUGAOyhIthen1SpyZ5moY2iYq5425GhC4sKFZpHcykzcIjopqVX48kf5HoPEfbPiyQamRGekpSpxzHCpyKIhKq1k0D03krGPOf0blNnisfJEDm372xQKbkoYX9Ia18XzB8oKRj2PC4hM5Gr38Vxfq1wvULbBAme+HPhBZ2lCqPsXWy+HOimlIxa04KZSGbB6ndlnWM7VDv5HBmgunYVgY5Zia+kftTSXbe2bYoqiQ49PtEYw2MismquAjGrpQL1A/Jxxd6esjBCwQObzUn9UBEGi1cN1GtIJd7M0G6wTKKUR41WguXC0IdlM0enfAqmS+pl/0YX/9wOSVcOJIIjg6MOxGfrlwXR9pLdD8uzG9+tKCjROvf3roWodKZ477YFBSYwfHjCz70ISz9gR8CdtfD/A1u6d4PZg0a5WySE2X94SPhKEzJbDsJB4uvWGtrBmdM0rI6DnsTrDxooNnob4BgUJLfaSlyV3yzsA6XmbyLBngpmvwpW30JITpsBjmJW1qvmg9znxctQAfE9jaWHpOALybh/zAZnUCHFIWNjo3HMgGaK1WguPLbyL+IL7WCihL5E9FtiAZWRJSaLMVNCCLH4WWZBn9rilPAnQF7iIN/ffTcxk2w1TGZkqEsyf6OpEarDNC0EJfYYMLyZBwWi08="

services:
  - docker

before_install:
  - git --version
  - sudo apt-add-repository ppa:brightbox/ruby-ng -y
  - sudo apt-get update
  - sudo apt-get install -f
  - sudo apt-get --yes install ruby2.5 ruby2.5-dev && sudo apt-get install -f
  - openssl aes-256-cbc -K $encrypted_5a45bd5412da_key -iv $encrypted_5a45bd5412da_iv -in key.json.enc -out /home/travis/build/key.json -d

install:
  - nvm install 8
  - sudo gem install fastlane
  - export TAG=`grep '"version":' package.json | cut -d\" -f4`
  - export ANDROID_VERSION_CODE=$((30000 + $TRAVIS_BUILD_NUMBER))
  - npm -g install cordova
  - npm -g install typescript
  - npm -g install cordova-set-version
  - npm install
  - cd server && npm install
  - cd ..

cache:
  bundler: true
  directories:
    - "node_modules"
    - "server/node_modules"
    - $HOME/.gradle

script:
  - npm run test:ci
  - npm run codacy:coverage -- --token $CODACY_KEY
  - npm run compodoc
  - ./push.sh
  - npm run build:web
  - npm run build:app
  - npm run build:server
  - docker build -t $DOCKER_REPO:$TAG-$TRAVIS_BUILD_NUMBER .
  - cd app
  - cordova platform add android
  - cordova-set-version -v $TAG -b $ANDROID_VERSION_CODE ./config.xml
  - cordova build android --release -- --keystore="./limahb.keystore" --storePassword=$ANDROID_KEYSTORE_STOREPASS --password=$ANDROID_KEYSTORE_PASS --alias=limahb

after_success:
  - docker login -u $DOCKER_USER -p "$DOCKER_PASS"
  - docker push $DOCKER_REPO:$TAG-$TRAVIS_BUILD_NUMBER
  - fastlane supply init --json_key /home/travis/build/key.json -p de.wildeligamanager.bremen
  - npm run createchangelog -- -v $ANDROID_VERSION_CODE
  - fastlane supply --apk /home/travis/build/RobertKitzing/liga-manager-ui/app/platforms/android/app/build/outputs/apk/release/app-release.apk --track beta -p de.wildeligamanager.bremen --json_key /home/travis/build/key.json