language: android
android:
  components:
    - build-tools-26.0.2
    - android-27

env:
  global:
    - DOCKER_USER=robertkitzing
    - DOCKER_REPO=robertkitzing/liga-manager-ui

services:
  - docker

install:
  - nvm install 8
  - export TAG=`grep '"version":' package.json | cut -d\" -f4`
  - yarn global add cordova
  - yarn global add typescript
  - yarn install
  - cd server && yarn install
  - cd ..

cache:
  directories:
    - "node_modules"
    - "server/node_modules"
    - $HOME/.gradle

script:
  - yarn run build:web
  - yarn run build:app
  - yarn run build:server
  - docker build -t $DOCKER_REPO:$TAG-$TRAVIS_BUILD_NUMBER .
  - cd app
  - cordova platform add android
  - cordova build android --release -- --keystore="./limahb.keystore" --storePassword=$ANDROID_KEYSTORE_STOREPASS --password=$ANDROID_KEYSTORE_PASS --alias=limahb

after_success:
  - docker login -u $DOCKER_USER -p "$DOCKER_PASS"
  - docker push $DOCKER_REPO:$TAG-$TRAVIS_BUILD_NUMBER

before_deploy:
  - git config --local user.name "travis ci"
  - git config --local user.email "travis@ci.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: "/home/travis/build/RobertKitzing/liga-manager-ui/app/platforms/android/app/build/outputs/apk/release/app-release.apk"
  skip_cleanup: true