volumes:
  team-logos:
  assets:

services:

  nginx:
    #image: robertkitzing/liga-manager-ui:next
    build: .
    environment:
      GOOGLE_MAPS_API_KEY: ""
      IMG_PROXY_HOST: imgproxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - team-logos:/var/www/logos
      - assets:/ui/browser/assets
    depends_on:
      - api

  imgproxy:
    image: ghcr.io/imgproxy/imgproxy:latest
    environment:
      IMGPROXY_USE_ETAG: false
      IMGPROXY_ALLOWED_SOURCES: local://
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: /lima
      IMGPROXY_ENABLE_AVIF_DETECTION: true
      IMGPROXY_ENABLE_WEBP_DETECTION: true
    depends_on:
      - api
      - nginx
    volumes:
      - team-logos:/lima/logos:ro
      - assets:/lima/assets:ro
  # dev-ui:
  #   image: node:lts-alpine
  #   user: 1000:1000
  #   ports:
  #     - "4200:4200"
  #   volumes:
  #     - .:/liga-manager-ui
  #   working_dir: /liga-manager-ui
  #   command: npx nx run liga-manager-ui-web:serve:development

  api:
    image: mklocke/liga-manager-api:latest
    env_file:
      - ./env/api.env 
    volumes:
      - team-logos:/var/www/logos
    depends_on:
      - mariadb
      - redis

  redis:
    image: redis:alpine

  mariadb:
    image: mariadb:10.3.12
    ports:
      - "3306:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
    env_file:
      - ./env/api.env 

  # postgres:
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: weblate
  #     POSTGRES_PASSWORD: weblate
  #   volumes: 
  #     - ./data/postgres:/var/lib/postgresql/data
  #   ports:
  #     - '5432:5432'
  
  # weblate:
  #   image: weblate/weblate:latest
  #   ports:
  #     - 8080:8080
  #   environment:
  #     WEBLATE_SITE_DOMAIN: weblate.example.com
  #     WEBLATE_ADMIN_PASSWORD: 123456
  #     REDIS_HOST: redis
  #     POSTGRES_PASSWORD: weblate
  #     POSTGRES_USER: weblate
  #     POSTGRES_DATABASE: weblate
  #     POSTGRES_HOST: postgres
  #     POSTGRES_PORT: 5432
  #     WEBLATE_API_RATELIMIT_ANON: '9999999/day'