volumes:
  team-logos:
  assets:

services:
  nginx:
    image: ${UI_IMAGE}:${UI_TAG}
    environment:
      GOOGLE_MAPS_API_KEY: ""
      IMG_PROXY_HOST: imgproxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - assets:/ui/browser/assets
    depends_on:
      - api
      - mariadb
      - redis

  api:
    container_name: lima-api
    image: mklocke/liga-manager-api:${API_TAG}
    env_file:
      - ./env/api.env
    volumes:
      - team-logos:/var/www/logos
    depends_on:
      - mariadb
      - redis
  
  imgproxy:
    image: ghcr.io/imgproxy/imgproxy:latest
    environment:
      IMGPROXY_USE_ETAG: false
      IMGPROXY_ALLOWED_SOURCES: local://
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: /lima
      IMGPROXY_ENABLE_AVIF_DETECTION: true
      IMGPROXY_ENABLE_WEBP_DETECTION: true
    depends_on:
      - api
      - liga-manager-ui
    volumes:
      - team-logos:/lima/logos:ro
      - assets:/lima/assets:ro

  redis:
    image: redis:alpine

  mariadb:
    image: mariadb:10.11
    env_file:
      - ./env/api.env
