volumes:
  team-logos:

services:
  nginx:
    image: robertkitzing/liga-manager-ui:next
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  api:
    container_name: lima-api
    image: mklocke/liga-manager-api
    env_file:
      - ./env/api.env 
    volumes:
      - team-logos:/var/www/logos
    depends_on:
      - mariadb
      - redis
  redis:
    image: redis:alpine

  mariadb:
    image: mariadb:10.11
    ports:
      - "3306:3306"
    env_file:
      - ./env/api.env 