volumes:
  team-logos:
  assets:

services:
  liga-manager-ui:
    #image: robertkitzing/liga-manager-ui:next
    build: .
    environment:
      GOOGLE_MAPS_API_KEY: ""
      IMG_PROXY_HOST: imgproxy
      USE_IMGPROXY: false
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - assets:/ui/browser/assets
      - team-logos:/ui/browser/logos
    depends_on:
      - api

  imgproxy:
    image: ghcr.io/imgproxy/imgproxy:latest
    ports:
      - "8080:8080"
    environment:
      IMGPROXY_USE_ETAG: false
      IMGPROXY_ALLOWED_SOURCES: local://
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: /lima
      IMGPROXY_ENABLE_AVIF_DETECTION: true
      IMGPROXY_ENABLE_WEBP_DETECTION: true
    depends_on:
      - api
      - liga-manager-ui
    volumes:
      - team-logos:/lima/logos:ro
      - assets:/lima/assets:ro

  api:
    image: mklocke/liga-manager-api:latest
    ports:
      - "9000:9000"
    env_file:
      - ./env/api.env 
    volumes:
      - team-logos:/var/www/logos
    depends_on:
      - mariadb
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  mariadb:
    image: mariadb:10.4
    ports:
      - "3306:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
    env_file:
      - ./env/api.env 