volumes:
  team-logos:
  mysql-data:

services:
  liga-manager-ui:
    build: .
    environment:
      GOOGLE_MAPS_API_KEY: ""
      USE_IMGPROXY: true
    ports:
      - "80:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://localhost/health || exit 1"]
      start_period: 1m
      start_interval: 5s
      interval: 1m
      timeout: 5s
  imgproxy:
    build:
      context: .
      dockerfile: Dockerfile.imgproxy
    volumes:
      - team-logos:/lima/logos:ro
    healthcheck:
      test: [ "CMD", "imgproxy", "health" ]
      timeout: "10s"
      interval: "10s"
      retries: 3
  api:
    container_name: lima-api
    image: mklocke/liga-manager-api:latest
    ports:
      - "9000:9000"
    environment:
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=123456
      - APP_BASE_URL=http://localhost:4200
      - DB_URL=pdo-mysql://lima:dev@mariadb/lima
      - EMAIL_SENDER_ADDRESS=noreply@example.com
      - EMAIL_SENDER_NAME=Wilde Liga Bremen
      - EMAIL_URL=smtp://lima:foobar@maildev:1025?verify_peer=0
      - JWT_SECRET=0123456789abcdef
      - LOG_LEVEL=warning
      - REDIS_HOST=redis
    volumes:
      - team-logos:/var/www/logos
    healthcheck:
      test: [ "CMD", "docker-php-healthcheck" ]
      start_period: 1m
      start_interval: 5s
      interval: 1m
      timeout: 5s
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  mariadb:
    image: mariadb:11.4
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=lima
      - MARIADB_USER=lima
      - MARIADB_PASSWORD=dev
      - MARIADB_ROOT_PASSWORD=dev
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 1m
      start_interval: 5s
      interval: 1m
      timeout: 5s
  maildev:
    image: maildev/maildev:latest
    ports:
      - "1080:1080"
    environment:
      - MAILDEV_INCOMING_USER=lima
      - MAILDEV_INCOMING_PASS=foobar
    healthcheck:
      test: [ "CMD", "wget", "-O", '-', 'http://127.0.0.1:1080/healthz' ]
      start_period: 1m
      start_interval: 5s
      interval: 1m
      timeout: 5s