services:
  ui:
    container_name: liga-manager-ui
    image: node:lts-alpine
    user: 1000:1000
    ports:
      - "4200:4200"
    volumes:
      - .:/liga-manager-ui
    working_dir: /liga-manager-ui
    tty: true
    # command: npm start
    
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - api-public:/var/www/api/public:ro
    depends_on:
      - ui
      - api
  
  api:
    image: mklocke/liga-manager-api
    user: www-data
    volumes:
      - api-public:/var/www/api/public
    env_file:
      - ./env/api.env 
    depends_on:
      - mariadb
      - redis
  
  redis:
    image: redis:4-alpine
  
  mariadb:
    image: mariadb:10.3.12
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    env_file:
      - ./env/api.env 

volumes:
  api-public: