version: '3'
services:
  # tests:
  #   image: node:10.15.3
  #   ports:
  #     - "9867:9867"
  #   volumes:
  #     - .:/usr/src/app
  #   working_dir: /usr/src/app
  #   command: npm test
  ui:
    image: node:lts-slim
    ports:
      - "3098:3098"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: tail -f /dev/null
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - api-public:/var/www/api/public:ro
    depends_on:
      - ui
      - api
  api:
    image: mklocke/liga-manager-api
    user: www-data
    volumes:
      - api-public:/var/www/api/public
    env_file:
      - ./env/api.env 
    depends_on:
      - mariadb
      - redis
  redis:
    image: redis:4-alpine
    ports:
      - "127.0.0.1:6379:6379"
  mariadb:
    image: mariadb:10.3.12
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    env_file:
      - ./env/api.env 
volumes:
  api-public: