volumes:
  team-logos:
  assets:

services:
  liga-manager-ui:
    image: ${UI_IMAGE}:${UI_TAG}
    environment:
      GOOGLE_MAPS_API_KEY: ""
      USE_IMGPROXY: false
    ports:
      - "80:80"
    volumes:
      - ./nginx.e2e.conf:/etc/nginx/conf.d/default.conf
      - assets:/ui/browser/assets
      - team-logos:/ui/browser/logos
    depends_on:
      - api
      - mariadb
      - redis

  api:
    container_name: lima-api
    image: mklocke/liga-manager-api:${API_TAG}
    env_file:
      - ./env/api.env
    volumes:
      - team-logos:/var/www/logos
    depends_on:
      - mariadb
      - redis

  redis:
    image: redis:alpine

  mariadb:
    image: mariadb:10.11
    env_file:
      - ./env/api.env
