volumes:
  team-logos:
  assets:
  mysql-data:

services:
  liga-manager-ui:
    image: ${UI_IMAGE}:${UI_TAG}
    environment:
      GOOGLE_MAPS_API_KEY: ""
      USE_IMGPROXY: false
    ports:
      - "80:80"
    volumes:
      - ./nginx.e2e.conf:/etc/nginx/conf.d/default.conf
      - assets:/ui/browser/assets
      - team-logos:/ui/browser/logos
    depends_on:
      - api
      - mariadb
      - redis

  api:
    container_name: lima-api
    image: mklocke/liga-manager-api:${API_TAG}
    environment:
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=123456
      - APP_BASE_URL=http://localhost
      - DB_URL=pdo-mysql://lima:dev@mariadb/lima
      - EMAIL_SENDER_ADDRESS=noreply@example.com
      - EMAIL_SENDER_NAME=Wilde Liga Bremen
      - EMAIL_URL=smtp://lima:foobar@maildev:1025?verify_peer=0
      - JWT_SECRET=0123456789abcdef
      - LOG_LEVEL=warning
      - REDIS_HOST=redis
    volumes:
      - team-logos:/var/www/logos
    healthcheck:
      test: [ "CMD", "docker-php-healthcheck" ]
      start_period: 1m
      start_interval: 5s
      interval: 1m
      timeout: 5s

  redis:
    image: redis:alpine

  mariadb:
    image: mariadb:11.4
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=lima
      - MARIADB_USER=lima
      - MARIADB_PASSWORD=dev
      - MARIADB_ROOT_PASSWORD=dev
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 1m
      start_interval: 5s
      interval: 1m
      timeout: 5s

  maildev:
    image: maildev/maildev:latest
    ports:
      - "1080:1080"
    environment:
      - MAILDEV_INCOMING_USER=lima
      - MAILDEV_INCOMING_PASS=foobar
    healthcheck:
      test: [ "CMD", "wget", "-O", '-', 'http://127.0.0.1:1080/healthz' ]
      start_period: 1m
      start_interval: 5s
      interval: 1m
      timeout: 5s