apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "liga-manager-ui.fullname" . }}-env
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "liga-manager-ui.labels" . | nindent 4 }}
data:
  {{- with .Values.env }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
