apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "liga-manager-ui.fullname" . }}-nginx
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "liga-manager-ui.labels" . | nindent 4 }}
data:
  default.conf: |
    upstream imgproxy {
      server {{ .Values.env.IMG_PROXY_HOST }}:{{ .Values.env.IMG_PROXY_PORT }};
    }
    server {
        listen {{ .Values.service.port }};
        server_name localhost;
        server_tokens off;
        gzip on;
        gzip_types application/json application/javascript image/webp image/png application/font-woff2 image/x-icon;

        include /nginx-ui-conf/nginx.ui.conf;

    }