name: 'Build'
inputs:
  docker-repo-ui:
    required: true
  docker-repo-imgproxy:
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - uses: actions/cache/restore@v4
      id: cache
      with:
        path: ./node_modules
        key: modules-${{ hashFiles('package-lock.json') }}
    - run: npx nx-cloud record -- nx run-many --target=build
      shell: bash
    - name: Build ui
      uses: docker/build-push-action@v5
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: .
        load: true
        tags: ${{ inputs.docker-repo-ui }}:e2e
    - name: Build imgproxy
      uses: docker/build-push-action@v5
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: .
        file: Dockerfile.imgproxy
        load: true
        tags: ${{ inputs.docker-repo-imgproxy }}:e2e
    - name: Save ui docker image
      run: docker save ${{ inputs.docker-repo-ui }}:e2e | gzip > /tmp/lima.tar
      shell: bash
    - name: Save imgproxy docker image
      run: docker save ${{ inputs.docker-repo-imgproxy }}:e2e | gzip > /tmp/imgproxy.tar
      shell: bash
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: lima-img
        path: /tmp/lima.tar
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: imgproxy-img
        path: /tmp/imgproxy.tar