export enum StorageKeys {

    ACCESS_TOKEN = 'ACCESS_TOKEN',
    ADMIN_SELECTED_MANAGE_TOURNAMENT = 'ADMIN_SELECTED_MANAGE_TOURNAMENT',
    SCHEDULE_SELECTED_MATCH_DAY_ID = 'SCHEDULE_SELECTED_MATCH_DAY_ID',
    SCHEDULE_SELECTED_TEAM_ID = 'SCHEDULE_SELECTED_TEAM_ID',
    TEAMS_MANAGMENT_SELECTED_TEAM = 'TEAMS_MANAGMENT_SELECTED_TEAM',
    TOURNAMENT_SELECTED_TOURNAMENT = 'TOURNAMENT_SELECTED_TOURNAMENT',
    LANGUAGE = 'LANGUAGE',
    SELECTED_PROGRESS_SEASON = 'SELECTED_PROGRESS_SEASON',
    SELECTED_HISTORY_SEASON = 'SELECTED_HISTORY_SEASON',
    SELECTED_MANAGE_SEASON = 'SELECTED_MANAGE_SEASON',
    DARK_MODE_APPEARANCE = 'DARK_MODE_APPEARANCE',
    THEME = 'THEME',

}