apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "imgproxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "imgproxy.labels" . | nindent 4 }}
data:
  {{- with .Values.env }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
