name: E2E Tests
on: [push, pull_request]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start Services
        run: docker compose -f docker-compose.e2e.yml up -d
      - name: Init Database
        run: docker exec lima-api lima migrations:migrate
      - name: Load Demo Data
        run: docker exec lima-api lima app:db:demo-data
      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_baseUrl: http://localhost
        with:
          browser: chrome
          working-directory: frontend