name: E2E Tests
on:
  workflow_dispatch:
    inputs:
      ui-image:
        description: 'UI Image'
        required: true
        default: robertkitzing/liga-manager-ui
      ui-image-tag:
        description: 'Tag for the UI Image'
        required: true
        default: 'latest'
      api-image-tag:
        description: 'Tag for the API Image'
        required: true
        default: 'latest'
jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [0, 1, 2, 3, 4 ,5]
    steps:
      - uses: actions/checkout@v4
      - name: Start Services
        uses: hoverkraft-tech/compose-action@v2.2.0
        env:
          UI_IMAGE: ${{ github.event.inputs.ui-image }}
          UI_TAG: ${{ github.event.inputs.ui-image-tag }}
          API_TAG: ${{ github.event.inputs.api-image-tag }}
        with:
          compose-file: "./docker-compose.e2e.yml"
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npx nx-cloud record -- nx e2e liga-manager-ui-web --config="baseUrl=http://localhost" --browser="chrome" --record --env.CYPRESS_RECORD_KEY="${{ secrets.CYPRESS_RECORD_KEY }}" --args="--parallel" --group chrome
      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-videos
          path: dist/cypress/apps/liga-manager-ui-web
