name: Main Action
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO_UI: robertkitzing/liga-manager-ui
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: ./package-lock.json
    - run: npm install
    - run: npm --prefix ./server/express install
    # - run: npm run build:angular:app
    - run: npm run build:server:express
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: server-express-dist
        path: |
          server/express/dist
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: server/express
        push: false
        tags: 
          - ${{ env.DOCKER_REPO_UI }}:latest
