name: Build
on: [push]
jobs:
  Main-Job:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO_UI: robertkitzing/liga-manager-ui
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: ./package-lock.json
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - run: npm install
    - run: npm --prefix ./server/express install
    - run: npm run build:server:express
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: server-express-dist
        path: |
          server/express/dist
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v3 
      with:
        token: ${{secrets.github_token}}
    - name: Build and push latest
      id: docker_build_latest
      uses: docker/build-push-action@v2
      with:
        context: server/express
        push: true
        tags: ${{ env.DOCKER_REPO_UI }}:latest
    - name: Build and push tagged
      id: docker_build_tag
      uses: docker/build-push-action@v2
      with:
        context: server/express
        push: true
        tags: ${{ env.DOCKER_REPO_UI }}:${{ steps.package-version.outputs.current-version}}-${{ steps.buildnumber.outputs.build_number }}
    # Android
    - run: npm run build:angular:app
    - name: Build Android app
      uses: oxr463/setup-cordova@0.0.2
      with:
        exec: |
          cd app && \
          cordova platform add android && \
          cordova-set-version -v ${{ steps.package-version.outputs.current-version}}-${{ steps.buildnumber.outputs.build_number }} -b ${{ steps.buildnumber.outputs.build_number }} ./config.xml && \
          cordova build --no-telemetry android --release -- --keystore="./limahb.keystore" --storePassword=$ANDROID_KEYSTORE_STOREPASS --password=$ANDROID_KEYSTORE_PASS --alias=limahb
    # - name: Build Android app
    #   working-directory: ./app
    #   uses: oxr463/setup-cordova@0.0.2
    #   with:
    #     exec: |
    #       cordova platform add android && \
    #       cordova-set-version -v ${{ steps.package-version.outputs.current-version}}-${{ steps.buildnumber.outputs.build_number }} -b ${{ steps.buildnumber.outputs.build_number }} ./config.xml && \
    #       cordova build --no-telemetry android --release -- --keystore="./limahb.keystore" --storePassword=$ANDROID_KEYSTORE_STOREPASS --password=$ANDROID_KEYSTORE_PASS --alias=limahb