name: Scheduled
on:
  workflow_dispatch:
env:
  HUSKY: 0

jobs:
  npm-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm audit --audit-level "high"
  npm-install:
    runs-on: ubuntu-latest
    steps:
    - uses: fregante/setup-git-user@v2
    - uses: stefanzweifel/git-auto-commit-action@v7
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - uses: actions/cache/restore@v4
      id: cache_restore
      with:
        path: ./node_modules
        key: modules-${{ hashFiles('package-lock.json') }}
    - run: npm install
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: ./node_modules
        key: modules-${{ hashFiles('package-lock.json') }}
#   test:
#     runs-on: ubuntu-latest
#     needs: 
#       - npm-install
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
#       - uses: actions/cache/restore@v4
#         id: cache
#         with:
#           path: ./node_modules
#           key: modules-${{ hashFiles('package-lock.json') }}
#       - run: npx nx-cloud record -- nx affected -t test
#   build:
#     runs-on: ubuntu-latest
#     needs: 
#       - npm-install
#     steps:
#       - uses: actions/checkout@v4
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
#       - uses: actions/cache/restore@v4
#         id: cache
#         with:
#           path: ./node_modules
#           key: modules-${{ hashFiles('package-lock.json') }}
#       - run: npx nx-cloud record -- nx run-many --target=build
#       - name: Build ui
#         uses: docker/build-push-action@v5
#         with:
#           cache-from: type=gha
#           cache-to: type=gha,mode=max
#           context: .
#           load: true
#           tags: ${{ env.DOCKER_REPO_UI }}:e2e
#       - name: Build imgproxy
#         uses: docker/build-push-action@v5
#         with:
#           cache-from: type=gha
#           cache-to: type=gha,mode=max
#           context: .
#           file: Dockerfile.imgproxy
#           load: true
#           tags: ${{ env.DOCKER_REPO_IMGPROXY }}:e2e
#       - name: Save ui docker image
#         run: docker save ${{ env.DOCKER_REPO_UI }}:e2e | gzip > /tmp/lima.tar
#       - name: Save imgproxy docker image
#         run: docker save ${{ env.DOCKER_REPO_IMGPROXY }}:e2e | gzip > /tmp/imgproxy.tar
#       - name: Upload artifact
#         uses: actions/upload-artifact@v4
#         with:
#           name: lima-img
#           path: /tmp/lima.tar
#       - name: Upload artifact
#         uses: actions/upload-artifact@v4
#         with:
#           name: imgproxy-img
#           path: /tmp/imgproxy.tar